### ISSUE TITLE
Labels of QuestionnaireItemQuality7pt contain fixed content

### ISSUE THREAD

**Issue by klaf1704** [TheFragebogen/TheFragebogen#4]
`QuestionnaireItemQuality7pt` has fixed content for all labels already set in the SVG.
It would be great to have make these configurable.

**Comment by dennisguse** [comment]
`function QuestionnaireItemQuality7pt(className, question, required, labels) {...}`
provides parameter label (`string[7]`) for the labels.

@klaf1704 Can you please test and verify?
I will wait for merging until you verified the change.
